version: '3.9'

services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: myapp_development
    networks:
      - fullstack

  backend:
    build: ./posts-api
    volumes:
      - ./posts-api:/backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/myapp_development"
    networks:
      - fullstack
    command: >
      bash -c "
        bin/rails db:create &&
        bin/rails db:migrate &&
        bundle exec rails server -b 0.0.0.0
      "

  frontend:
    build: ./post-fe
    volumes:
      - ./post-fe:/frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - fullstack

networks:
  fullstack:
